//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.1378.
// 
namespace GentagDemo.petWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="petWSSoapHttp", Namespace="http://petPackage/")]
    public partial class petWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public petWS() {
            this.Url = "http://crius.dyndns.org:8888/GentagDemo/petWSSoapHttpPort";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://petPackage//authorize", RequestElementName="authorizeElement", RequestNamespace="http://petPackage/types/", ResponseElementName="authorizeResponseElement", ResponseNamespace="http://petPackage/types/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result", IsNullable=true)]
        public errorMessage authorize([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_1) {
            object[] results = this.Invoke("authorize", new object[] {
                        String_1});
            return ((errorMessage)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginauthorize(string String_1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("authorize", new object[] {
                        String_1}, callback, asyncState);
        }
        
        /// <remarks/>
        public errorMessage Endauthorize(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((errorMessage)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://petPackage//changePassword", RequestElementName="changePasswordElement", RequestNamespace="http://petPackage/types/", ResponseElementName="changePasswordResponseElement", ResponseNamespace="http://petPackage/types/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public bool changePassword([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_3) {
            object[] results = this.Invoke("changePassword", new object[] {
                        String_1,
                        String_2,
                        String_3});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginchangePassword(string String_1, string String_2, string String_3, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("changePassword", new object[] {
                        String_1,
                        String_2,
                        String_3}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndchangePassword(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://petPackage//changePasswordTagCode", RequestElementName="changePasswordTagCodeElement", RequestNamespace="http://petPackage/types/", ResponseElementName="changePasswordTagCodeResponseElement", ResponseNamespace="http://petPackage/types/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public bool changePasswordTagCode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_3) {
            object[] results = this.Invoke("changePasswordTagCode", new object[] {
                        String_1,
                        String_2,
                        String_3});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginchangePasswordTagCode(string String_1, string String_2, string String_3, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("changePasswordTagCode", new object[] {
                        String_1,
                        String_2,
                        String_3}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndchangePasswordTagCode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://petPackage//retrievePetInformation", RequestElementName="retrievePetInformationElement", RequestNamespace="http://petPackage/types/", ResponseElementName="retrievePetInformationResponseElement", ResponseNamespace="http://petPackage/types/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result", IsNullable=true)]
        public petInfo retrievePetInformation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_2, float float_3, float float_4) {
            object[] results = this.Invoke("retrievePetInformation", new object[] {
                        String_1,
                        String_2,
                        float_3,
                        float_4});
            return ((petInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginretrievePetInformation(string String_1, string String_2, float float_3, float float_4, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("retrievePetInformation", new object[] {
                        String_1,
                        String_2,
                        float_3,
                        float_4}, callback, asyncState);
        }
        
        /// <remarks/>
        public petInfo EndretrievePetInformation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((petInfo)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://petPackage//retrievePetInformationTagCode", RequestElementName="retrievePetInformationTagCodeElement", RequestNamespace="http://petPackage/types/", ResponseElementName="retrievePetInformationTagCodeResponseElement", ResponseNamespace="http://petPackage/types/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result", IsNullable=true)]
        public petInfo retrievePetInformationTagCode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_2, float float_3, float float_4) {
            object[] results = this.Invoke("retrievePetInformationTagCode", new object[] {
                        String_1,
                        String_2,
                        float_3,
                        float_4});
            return ((petInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginretrievePetInformationTagCode(string String_1, string String_2, float float_3, float float_4, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("retrievePetInformationTagCode", new object[] {
                        String_1,
                        String_2,
                        float_3,
                        float_4}, callback, asyncState);
        }
        
        /// <remarks/>
        public petInfo EndretrievePetInformationTagCode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((petInfo)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://petPackage//updatePetInformation", RequestElementName="updatePetInformationElement", RequestNamespace="http://petPackage/types/", ResponseElementName="updatePetInformationResponseElement", ResponseNamespace="http://petPackage/types/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result", IsNullable=true)]
        public errorMessage updatePetInformation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] petInfo petInfo_1) {
            object[] results = this.Invoke("updatePetInformation", new object[] {
                        petInfo_1});
            return ((errorMessage)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdatePetInformation(petInfo petInfo_1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updatePetInformation", new object[] {
                        petInfo_1}, callback, asyncState);
        }
        
        /// <remarks/>
        public errorMessage EndupdatePetInformation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((errorMessage)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://petPackage//updatePetInformationTagCode", RequestElementName="updatePetInformationTagCodeElement", RequestNamespace="http://petPackage/types/", ResponseElementName="updatePetInformationTagCodeResponseElement", ResponseNamespace="http://petPackage/types/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result", IsNullable=true)]
        public errorMessage updatePetInformationTagCode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] petInfo petInfo_1) {
            object[] results = this.Invoke("updatePetInformationTagCode", new object[] {
                        petInfo_1});
            return ((errorMessage)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdatePetInformationTagCode(petInfo petInfo_1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updatePetInformationTagCode", new object[] {
                        petInfo_1}, callback, asyncState);
        }
        
        /// <remarks/>
        public errorMessage EndupdatePetInformationTagCode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((errorMessage)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://petPackage/types/")]
    public partial class errorMessage {
        
        private string errorMessage1Field;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errorMessage", IsNullable=true)]
        public string errorMessage1 {
            get {
                return this.errorMessage1Field;
            }
            set {
                this.errorMessage1Field = value;
            }
        }
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://petPackage/types/")]
    public partial class petInfo {
        
        private string passwordField;
        
        private string workPhoneField;
        
        private string vetNameField;
        
        private string ownerField;
        
        private string breedField;
        
        private bool existsField;
        
        private string homePhoneField;
        
        private string rfidNumField;
        
        private string cellPhoneField;
        
        private string medicalNeedsField;
        
        private string contactInfoField;
        
        private string vetPhoneField;
        
        private int rewardField;
        
        private byte[] imageField;
        
        private string emailField;
        
        private string vetAddressField;
        
        private string nameField;
        
        private string medicationsField;
        
        private string preferredFoodField;
        
        private string tagCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string workPhone {
            get {
                return this.workPhoneField;
            }
            set {
                this.workPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vetName {
            get {
                return this.vetNameField;
            }
            set {
                this.vetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string breed {
            get {
                return this.breedField;
            }
            set {
                this.breedField = value;
            }
        }
        
        /// <remarks/>
        public bool exists {
            get {
                return this.existsField;
            }
            set {
                this.existsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string homePhone {
            get {
                return this.homePhoneField;
            }
            set {
                this.homePhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rfidNum {
            get {
                return this.rfidNumField;
            }
            set {
                this.rfidNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cellPhone {
            get {
                return this.cellPhoneField;
            }
            set {
                this.cellPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string medicalNeeds {
            get {
                return this.medicalNeedsField;
            }
            set {
                this.medicalNeedsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string contactInfo {
            get {
                return this.contactInfoField;
            }
            set {
                this.contactInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vetPhone {
            get {
                return this.vetPhoneField;
            }
            set {
                this.vetPhoneField = value;
            }
        }
        
        /// <remarks/>
        public int reward {
            get {
                return this.rewardField;
            }
            set {
                this.rewardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vetAddress {
            get {
                return this.vetAddressField;
            }
            set {
                this.vetAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string medications {
            get {
                return this.medicationsField;
            }
            set {
                this.medicationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string preferredFood {
            get {
                return this.preferredFoodField;
            }
            set {
                this.preferredFoodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tagCode {
            get {
                return this.tagCodeField;
            }
            set {
                this.tagCodeField = value;
            }
        }
    }
}
