//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.1433.
// 
namespace DHL_Demo.DHLDemoWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DhlDemoWSSoapHttp", Namespace="http://dhlDemo/")]
    public partial class DhlDemoWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public DhlDemoWS() {
            this.Url = "http://crius.dyndns.org:8888/GentagDemo/DhlDemoWSSoapHttpPort";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://dhlDemo/", ResponseNamespace="http://dhlDemo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public packageInfo getPackageInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string RFIDNum) {
            object[] results = this.Invoke("getPackageInfo", new object[] {
                        RFIDNum});
            return ((packageInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPackageInfo(string RFIDNum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPackageInfo", new object[] {
                        RFIDNum}, callback, asyncState);
        }
        
        /// <remarks/>
        public packageInfo EndgetPackageInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((packageInfo)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://dhlDemo/", ResponseNamespace="http://dhlDemo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public packageInfo scanPackage([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] packageScan newScan) {
            object[] results = this.Invoke("scanPackage", new object[] {
                        newScan});
            return ((packageInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginscanPackage(packageScan newScan, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("scanPackage", new object[] {
                        newScan}, callback, asyncState);
        }
        
        /// <remarks/>
        public packageInfo EndscanPackage(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((packageInfo)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://dhlDemo/", ResponseNamespace="http://dhlDemo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public bool setPackageInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] packageInfo newPackage) {
            object[] results = this.Invoke("setPackageInfo", new object[] {
                        newPackage});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetPackageInfo(packageInfo newPackage, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setPackageInfo", new object[] {
                        newPackage}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndsetPackageInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dhlDemo/")]
    public partial class packageInfo {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RFIDNum;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string deliveryAddress2;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string deliveryAddress;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string recipientPager;
        
        /// <remarks/>
        public bool exists;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string recipientEmail;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string trackingNumber;
        
        /// <remarks/>
        public float longitude;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string country;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string state;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string zip;
        
        /// <remarks/>
        public float latitude;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string city;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string recipient;
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dhlDemo/")]
    public partial class packageScan {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RFIDNum;
        
        /// <remarks/>
        public float longitude;
        
        /// <remarks/>
        public int actionTaken;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string scannerID;
        
        /// <remarks/>
        public long scanTime;
        
        /// <remarks/>
        public float latitude;
    }
}
