//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1318
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1318.
// 
#pragma warning disable 1591

namespace WineEntryClient.petWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1318")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="petWSSoapHttp", Namespace="http://petPackage/")]
    public partial class petWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback enterPetInformationOperationCompleted;
        
        private System.Threading.SendOrPostCallback retrievePetInformationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public petWS() {
            this.Url = global::WineEntryClient.Properties.Settings.Default.WineEntryClient_petWS_petWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event enterPetInformationCompletedEventHandler enterPetInformationCompleted;
        
        /// <remarks/>
        public event retrievePetInformationCompletedEventHandler retrievePetInformationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://petPackage//enterPetInformation", RequestElementName="enterPetInformationElement", RequestNamespace="http://petPackage/types/", ResponseElementName="enterPetInformationResponseElement", ResponseNamespace="http://petPackage/types/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public bool enterPetInformation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] petInfo rfidNums) {
            object[] results = this.Invoke("enterPetInformation", new object[] {
                        rfidNums});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void enterPetInformationAsync(petInfo rfidNums) {
            this.enterPetInformationAsync(rfidNums, null);
        }
        
        /// <remarks/>
        public void enterPetInformationAsync(petInfo rfidNums, object userState) {
            if ((this.enterPetInformationOperationCompleted == null)) {
                this.enterPetInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenterPetInformationOperationCompleted);
            }
            this.InvokeAsync("enterPetInformation", new object[] {
                        rfidNums}, this.enterPetInformationOperationCompleted, userState);
        }
        
        private void OnenterPetInformationOperationCompleted(object arg) {
            if ((this.enterPetInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enterPetInformationCompleted(this, new enterPetInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://petPackage//retrievePetInformation", RequestElementName="retrievePetInformationElement", RequestNamespace="http://petPackage/types/", ResponseElementName="retrievePetInformationResponseElement", ResponseNamespace="http://petPackage/types/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result", IsNullable=true)]
        public petInfo retrievePetInformation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_2, float float_3, float float_4) {
            object[] results = this.Invoke("retrievePetInformation", new object[] {
                        String_1,
                        String_2,
                        float_3,
                        float_4});
            return ((petInfo)(results[0]));
        }
        
        /// <remarks/>
        public void retrievePetInformationAsync(string String_1, string String_2, float float_3, float float_4) {
            this.retrievePetInformationAsync(String_1, String_2, float_3, float_4, null);
        }
        
        /// <remarks/>
        public void retrievePetInformationAsync(string String_1, string String_2, float float_3, float float_4, object userState) {
            if ((this.retrievePetInformationOperationCompleted == null)) {
                this.retrievePetInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretrievePetInformationOperationCompleted);
            }
            this.InvokeAsync("retrievePetInformation", new object[] {
                        String_1,
                        String_2,
                        float_3,
                        float_4}, this.retrievePetInformationOperationCompleted, userState);
        }
        
        private void OnretrievePetInformationOperationCompleted(object arg) {
            if ((this.retrievePetInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retrievePetInformationCompleted(this, new retrievePetInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1318")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://petPackage/types/")]
    public partial class petInfo {
        
        private string contactInfoField;
        
        private string ownerField;
        
        private byte[] imageField;
        
        private string breedField;
        
        private bool existsField;
        
        private string phoneNumberField;
        
        private string rfidNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string contactInfo {
            get {
                return this.contactInfoField;
            }
            set {
                this.contactInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string breed {
            get {
                return this.breedField;
            }
            set {
                this.breedField = value;
            }
        }
        
        /// <remarks/>
        public bool exists {
            get {
                return this.existsField;
            }
            set {
                this.existsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rfidNum {
            get {
                return this.rfidNumField;
            }
            set {
                this.rfidNumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1318")]
    public delegate void enterPetInformationCompletedEventHandler(object sender, enterPetInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1318")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enterPetInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enterPetInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1318")]
    public delegate void retrievePetInformationCompletedEventHandler(object sender, retrievePetInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1318")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retrievePetInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retrievePetInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public petInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((petInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591