//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.1433.
// 
namespace GentagDemo.assayWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AssayWSSoapHttp", Namespace="http://assayPackage/")]
    public partial class AssayWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public AssayWS() {
            this.Url = "http://id1.gentag.com:7777/GentagDemo/AssayWSSoapHttpPort";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://assayPackage//retrieveAssayInformation", RequestElementName="retrieveAssayInformationElement", RequestNamespace="http://assayPackage/", ResponseElementName="retrieveAssayInformationResponseElement", ResponseNamespace="http://assayPackage/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result", IsNullable=true)]
        public assayInfo retrieveAssayInformation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfidNum, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string phoneID) {
            object[] results = this.Invoke("retrieveAssayInformation", new object[] {
                        rfidNum,
                        phoneID});
            return ((assayInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginretrieveAssayInformation(string rfidNum, string phoneID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("retrieveAssayInformation", new object[] {
                        rfidNum,
                        phoneID}, callback, asyncState);
        }
        
        /// <remarks/>
        public assayInfo EndretrieveAssayInformation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((assayInfo)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://assayPackage//submitAssayResult", RequestElementName="submitAssayResultElement", RequestNamespace="http://assayPackage/", ResponseElementName="submitAssayResultResponseElement", ResponseNamespace="http://assayPackage/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result", IsNullable=true)]
        public assayResultResponse submitAssayResult([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_2, int int_3) {
            object[] results = this.Invoke("submitAssayResult", new object[] {
                        String_1,
                        String_2,
                        int_3});
            return ((assayResultResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsubmitAssayResult(string String_1, string String_2, int int_3, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("submitAssayResult", new object[] {
                        String_1,
                        String_2,
                        int_3}, callback, asyncState);
        }
        
        /// <remarks/>
        public assayResultResponse EndsubmitAssayResult(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((assayResultResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://assayPackage/")]
    public partial class assayInfo {
        
        /// <remarks/>
        public int timer;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string afterMessage;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] descriptionImage;
        
        /// <remarks/>
        public bool exists;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sessionID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resultImages", IsNullable=true)]
        public assayImage[] resultImages;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string beforeMessage;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rfidNum;
        
        /// <remarks/>
        public bool needRetry;
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://assayPackage/")]
    public partial class assayImage {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] image;
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://assayPackage/")]
    public partial class assayResultResponse {
        
        /// <remarks/>
        public bool success;
        
        /// <remarks/>
        public bool needRetry;
    }
}
