//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.312.
// 
namespace GentagDemo.org.dyndns.crius {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GetDatesWSSoapHttp", Namespace="http://datespackage/")]
    public partial class GetDatesWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public GetDatesWS() {
            this.Url = "http://crius.dyndns.org:8888/JavaWebService-GetDates-context-root/GetDatesWSSoapH" +
                "ttpPort";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://datespackage/", ResponseNamespace="http://datespackage/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public bool callIn([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string UID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lat, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string longit, long timeSinceLastReading) {
            object[] results = this.Invoke("callIn", new object[] {
                        UID,
                        lat,
                        longit,
                        timeSinceLastReading});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincallIn(string UID, string lat, string longit, long timeSinceLastReading, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("callIn", new object[] {
                        UID,
                        lat,
                        longit,
                        timeSinceLastReading}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndcallIn(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://datespackage/", ResponseNamespace="http://datespackage/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public bool checkInteraction([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string drugID) {
            object[] results = this.Invoke("checkInteraction", new object[] {
                        ID,
                        drugID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincheckInteraction(string ID, string drugID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("checkInteraction", new object[] {
                        ID,
                        drugID}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndcheckInteraction(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://datespackage/", ResponseNamespace="http://datespackage/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string getDescription([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string RFIDNum) {
            object[] results = this.Invoke("getDescription", new object[] {
                        RFIDNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetDescription(string RFIDNum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getDescription", new object[] {
                        RFIDNum}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetDescription(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://datespackage/", ResponseNamespace="http://datespackage/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public GetDates getInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ID, bool isDrug) {
            object[] results = this.Invoke("getInfo", new object[] {
                        ID,
                        isDrug});
            return ((GetDates)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetInfo(string ID, bool isDrug, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getInfo", new object[] {
                        ID,
                        isDrug}, callback, asyncState);
        }
        
        /// <remarks/>
        public GetDates EndgetInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetDates)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://datespackage/", ResponseNamespace="http://datespackage/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", DataType="base64Binary", IsNullable=true)]
        public byte[] getPicture([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ID, bool isDrug) {
            object[] results = this.Invoke("getPicture", new object[] {
                        ID,
                        isDrug});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPicture(string ID, bool isDrug, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPicture", new object[] {
                        ID,
                        isDrug}, callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndgetPicture(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://datespackage/", ResponseNamespace="http://datespackage/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string getRoute([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string RFIDNum) {
            object[] results = this.Invoke("getRoute", new object[] {
                        RFIDNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRoute(string RFIDNum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRoute", new object[] {
                        RFIDNum}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetRoute(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://datespackage/", ResponseNamespace="http://datespackage/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] getSince(long timestamp) {
            object[] results = this.Invoke("getSince", new object[] {
                        timestamp});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetSince(long timestamp, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getSince", new object[] {
                        timestamp}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetSince(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://datespackage/", ResponseNamespace="http://datespackage/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public bool isAuthenticated([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string RFIDNum, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string UID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lat, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string longit) {
            object[] results = this.Invoke("isAuthenticated", new object[] {
                        RFIDNum,
                        UID,
                        lat,
                        longit});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginisAuthenticated(string RFIDNum, string UID, string lat, string longit, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("isAuthenticated", new object[] {
                        RFIDNum,
                        UID,
                        lat,
                        longit}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndisAuthenticated(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datespackage/")]
    public partial class GetDates {
        
        private string nameField;
        
        private string descField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
    }
}
