//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1378.
// 
#pragma warning disable 1591

namespace Gentag_Pet_Entry_Client.petWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="petWSSoapHttp", Namespace="http://petPackage/")]
    public partial class petWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback changePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertOrUpdatePetInformationOperationCompleted;
        
        private System.Threading.SendOrPostCallback retrievePetInformationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public petWS() {
            this.Url = global::Gentag_Pet_Entry_Client.Properties.Settings.Default.Gentag_Pet_Entry_Client_petWS_petWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event changePasswordCompletedEventHandler changePasswordCompleted;
        
        /// <remarks/>
        public event insertOrUpdatePetInformationCompletedEventHandler insertOrUpdatePetInformationCompleted;
        
        /// <remarks/>
        public event retrievePetInformationCompletedEventHandler retrievePetInformationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://petPackage//changePassword", RequestElementName="changePasswordElement", RequestNamespace="http://petPackage/types/", ResponseElementName="changePasswordResponseElement", ResponseNamespace="http://petPackage/types/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public bool changePassword([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_3) {
            object[] results = this.Invoke("changePassword", new object[] {
                        String_1,
                        String_2,
                        String_3});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void changePasswordAsync(string String_1, string String_2, string String_3) {
            this.changePasswordAsync(String_1, String_2, String_3, null);
        }
        
        /// <remarks/>
        public void changePasswordAsync(string String_1, string String_2, string String_3, object userState) {
            if ((this.changePasswordOperationCompleted == null)) {
                this.changePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchangePasswordOperationCompleted);
            }
            this.InvokeAsync("changePassword", new object[] {
                        String_1,
                        String_2,
                        String_3}, this.changePasswordOperationCompleted, userState);
        }
        
        private void OnchangePasswordOperationCompleted(object arg) {
            if ((this.changePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.changePasswordCompleted(this, new changePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://petPackage//insertOrUpdatePetInformation", RequestElementName="insertOrUpdatePetInformationElement", RequestNamespace="http://petPackage/types/", ResponseElementName="insertOrUpdatePetInformationResponseElement", ResponseNamespace="http://petPackage/types/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result", IsNullable=true)]
        public errorMessage insertOrUpdatePetInformation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] petInfo petInfo_1) {
            object[] results = this.Invoke("insertOrUpdatePetInformation", new object[] {
                        petInfo_1});
            return ((errorMessage)(results[0]));
        }
        
        /// <remarks/>
        public void insertOrUpdatePetInformationAsync(petInfo petInfo_1) {
            this.insertOrUpdatePetInformationAsync(petInfo_1, null);
        }
        
        /// <remarks/>
        public void insertOrUpdatePetInformationAsync(petInfo petInfo_1, object userState) {
            if ((this.insertOrUpdatePetInformationOperationCompleted == null)) {
                this.insertOrUpdatePetInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertOrUpdatePetInformationOperationCompleted);
            }
            this.InvokeAsync("insertOrUpdatePetInformation", new object[] {
                        petInfo_1}, this.insertOrUpdatePetInformationOperationCompleted, userState);
        }
        
        private void OninsertOrUpdatePetInformationOperationCompleted(object arg) {
            if ((this.insertOrUpdatePetInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertOrUpdatePetInformationCompleted(this, new insertOrUpdatePetInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://petPackage//retrievePetInformation", RequestElementName="retrievePetInformationElement", RequestNamespace="http://petPackage/types/", ResponseElementName="retrievePetInformationResponseElement", ResponseNamespace="http://petPackage/types/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result", IsNullable=true)]
        public petInfo retrievePetInformation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_2, float float_3, float float_4, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_5) {
            object[] results = this.Invoke("retrievePetInformation", new object[] {
                        String_1,
                        String_2,
                        float_3,
                        float_4,
                        String_5});
            return ((petInfo)(results[0]));
        }
        
        /// <remarks/>
        public void retrievePetInformationAsync(string String_1, string String_2, float float_3, float float_4, string String_5) {
            this.retrievePetInformationAsync(String_1, String_2, float_3, float_4, String_5, null);
        }
        
        /// <remarks/>
        public void retrievePetInformationAsync(string String_1, string String_2, float float_3, float float_4, string String_5, object userState) {
            if ((this.retrievePetInformationOperationCompleted == null)) {
                this.retrievePetInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretrievePetInformationOperationCompleted);
            }
            this.InvokeAsync("retrievePetInformation", new object[] {
                        String_1,
                        String_2,
                        float_3,
                        float_4,
                        String_5}, this.retrievePetInformationOperationCompleted, userState);
        }
        
        private void OnretrievePetInformationOperationCompleted(object arg) {
            if ((this.retrievePetInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retrievePetInformationCompleted(this, new retrievePetInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1378")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://petPackage/types/")]
    public partial class petInfo {
        
        private string passwordField;
        
        private string workPhoneField;
        
        private string vetNameField;
        
        private string ownerField;
        
        private string breedField;
        
        private bool existsField;
        
        private string homePhoneField;
        
        private string rfidNumField;
        
        private string cellPhoneField;
        
        private string medicalNeedsField;
        
        private string contactInfoField;
        
        private string vetPhoneField;
        
        private int rewardField;
        
        private byte[] imageField;
        
        private string emailField;
        
        private string vetAddressField;
        
        private string nameField;
        
        private string medicationsField;
        
        private string preferredFoodField;
        
        private string tagCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string workPhone {
            get {
                return this.workPhoneField;
            }
            set {
                this.workPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vetName {
            get {
                return this.vetNameField;
            }
            set {
                this.vetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string breed {
            get {
                return this.breedField;
            }
            set {
                this.breedField = value;
            }
        }
        
        /// <remarks/>
        public bool exists {
            get {
                return this.existsField;
            }
            set {
                this.existsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string homePhone {
            get {
                return this.homePhoneField;
            }
            set {
                this.homePhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rfidNum {
            get {
                return this.rfidNumField;
            }
            set {
                this.rfidNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cellPhone {
            get {
                return this.cellPhoneField;
            }
            set {
                this.cellPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string medicalNeeds {
            get {
                return this.medicalNeedsField;
            }
            set {
                this.medicalNeedsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string contactInfo {
            get {
                return this.contactInfoField;
            }
            set {
                this.contactInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vetPhone {
            get {
                return this.vetPhoneField;
            }
            set {
                this.vetPhoneField = value;
            }
        }
        
        /// <remarks/>
        public int reward {
            get {
                return this.rewardField;
            }
            set {
                this.rewardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vetAddress {
            get {
                return this.vetAddressField;
            }
            set {
                this.vetAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string medications {
            get {
                return this.medicationsField;
            }
            set {
                this.medicationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string preferredFood {
            get {
                return this.preferredFoodField;
            }
            set {
                this.preferredFoodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tagCode {
            get {
                return this.tagCodeField;
            }
            set {
                this.tagCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1378")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://petPackage/types/")]
    public partial class errorMessage {
        
        private string errorMessage1Field;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errorMessage", IsNullable=true)]
        public string errorMessage1 {
            get {
                return this.errorMessage1Field;
            }
            set {
                this.errorMessage1Field = value;
            }
        }
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void changePasswordCompletedEventHandler(object sender, changePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class changePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal changePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void insertOrUpdatePetInformationCompletedEventHandler(object sender, insertOrUpdatePetInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertOrUpdatePetInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertOrUpdatePetInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public errorMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((errorMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void retrievePetInformationCompletedEventHandler(object sender, retrievePetInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retrievePetInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retrievePetInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public petInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((petInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591