#!/bin/bash

# m5 to dinero trace file translator
#python m5ToDin.py trace/gupsStream trace/gups.din

# run dineroIV to get l3 cache stats
#./dineroIV -informat d -l1-usize 16M -l1-ubsize 64 -l1-uassoc 16 -l1-upfdist 3 < trace/gups.din > stats/l3-cache.txt

# run dineroIV-w-misstrace to generate L3 miss traces
#./dineroIV-w-misstrace -informat d -l1-usize 16M -l1-ubsize 64 -l1-uassoc 16 -l1-upfdist 3 < trace/gups.din > trace/gups.din.miss

# generate miss trace file for ds2
# generate miss trace file for dimm caches
# address mapping policy options:
# SDRAM_HIPERF_MAP
# SDRAM_BASE_MAP
# CLOSE_PAGE_BASELINE
# CLOSE_PAGE_BASELINE_OPT
# CLOSE_PAGE_LOW_LOCALITY
# CLOSE_PAGE_HIGH_LOCALITY
infile="trace/gups.din.miss"
ds2file="trace/gups-miss.trace"
dinerofile="trace/gups-miss.din"
addressmapping="CLOSE_PAGE_HIGH_LOCALITY"
echo $addressmapping
#python dinMiss.py $infile $ds2file $dinerofile $addressmapping

# run dineroIV to get L4 cache stats
./dineroIV -informat d -l1-usize 64M -l1-ubsize 256 -l1-uassoc 16 < trace/gups-miss.din > stats/l4-cache.txt

# run dineroIV to sim dimm caches
size="8M"
bsize=256
assoc=16
i=0
while [ $i -le 3 ]
do
	echo "dimm-cache $i"
	./dineroIV -informat d -l1-usize $size -l1-ubsize $bsize -l1-uassoc $assoc < trace/gups-miss.din.$addressmapping.$i > stats/dimm-cache.$addressmapping.$bsize.$i
	echo "dimm-cache $i DONE"

	i=$(( $i+1 ))
done
