//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.1433.
// 
namespace LookupCore.assayWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AssayWSSoapHttp", Namespace="http://assayPackage/")]
    public partial class AssayWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public AssayWS() {
            this.Url = "http://id1.gentag.com:7777/GentagDemo/AssayWSSoapHttpPort";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://assayPackage//retrieveAssayInformation", RequestElementName="retrieveAssayInformationElement", RequestNamespace="http://assayPackage/", ResponseElementName="retrieveAssayInformationResponseElement", ResponseNamespace="http://assayPackage/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result", IsNullable=true)]
        public assayInfo retrieveAssayInformation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfidNum, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string phoneID) {
            object[] results = this.Invoke("retrieveAssayInformation", new object[] {
                        rfidNum,
                        phoneID});
            return ((assayInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginretrieveAssayInformation(string rfidNum, string phoneID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("retrieveAssayInformation", new object[] {
                        rfidNum,
                        phoneID}, callback, asyncState);
        }
        
        /// <remarks/>
        public assayInfo EndretrieveAssayInformation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((assayInfo)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://assayPackage//submitAssayResult", RequestElementName="submitAssayResultElement", RequestNamespace="http://assayPackage/", ResponseElementName="submitAssayResultResponseElement", ResponseNamespace="http://assayPackage/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result", IsNullable=true)]
        public assayResultResponse submitAssayResult([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string String_2, int int_3) {
            object[] results = this.Invoke("submitAssayResult", new object[] {
                        String_1,
                        String_2,
                        int_3});
            return ((assayResultResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsubmitAssayResult(string String_1, string String_2, int int_3, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("submitAssayResult", new object[] {
                        String_1,
                        String_2,
                        int_3}, callback, asyncState);
        }
        
        /// <remarks/>
        public assayResultResponse EndsubmitAssayResult(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((assayResultResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://assayPackage/")]
    public partial class assayInfo {
        
        private int timerField;
        
        private string afterMessageField;
        
        private byte[] descriptionImageField;
        
        private bool existsField;
        
        private string sessionIDField;
        
        private assayImage[] resultImagesField;
        
        private string beforeMessageField;
        
        private string rfidNumField;
        
        private bool needRetryField;
        
        /// <remarks/>
        public int timer {
            get {
                return this.timerField;
            }
            set {
                this.timerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string afterMessage {
            get {
                return this.afterMessageField;
            }
            set {
                this.afterMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] descriptionImage {
            get {
                return this.descriptionImageField;
            }
            set {
                this.descriptionImageField = value;
            }
        }
        
        /// <remarks/>
        public bool exists {
            get {
                return this.existsField;
            }
            set {
                this.existsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resultImages", IsNullable=true)]
        public assayImage[] resultImages {
            get {
                return this.resultImagesField;
            }
            set {
                this.resultImagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string beforeMessage {
            get {
                return this.beforeMessageField;
            }
            set {
                this.beforeMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rfidNum {
            get {
                return this.rfidNumField;
            }
            set {
                this.rfidNumField = value;
            }
        }
        
        /// <remarks/>
        public bool needRetry {
            get {
                return this.needRetryField;
            }
            set {
                this.needRetryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://assayPackage/")]
    public partial class assayImage {
        
        private byte[] imageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://assayPackage/")]
    public partial class assayResultResponse {
        
        private bool successField;
        
        private bool needRetryField;
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public bool needRetry {
            get {
                return this.needRetryField;
            }
            set {
                this.needRetryField = value;
            }
        }
    }
}
