//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentagDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GentagDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Alpha.
        /// </summary>
        internal static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assay not found..
        /// </summary>
        internal static string AssayNotFound {
            get {
                return ResourceManager.GetString("AssayNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @.
        /// </summary>
        internal static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap blank {
            get {
                object obj = ResourceManager.GetObject("blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Problem.
        /// </summary>
        internal static string ConnectionProblem {
            get {
                return ResourceManager.GetString("ConnectionProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled, currently VarioSens is not compatible with the Sirit reader..
        /// </summary>
        internal static string DisabledVarioSens {
            get {
                return ResourceManager.GetString("DisabledVarioSens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! 
        ///This drug should not be taken by this patient..
        /// </summary>
        internal static string DrugInteractionWarningMessage {
            get {
                return ResourceManager.GetString("DrugInteractionWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string emptyString {
            get {
                return ResourceManager.GetString("emptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure that the Sirit reader is completely inserted.
        /// </summary>
        internal static string error1 {
            get {
                return ResourceManager.GetString("error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to communicate with Sirit reader.
        /// </summary>
        internal static string error2 {
            get {
                return ResourceManager.GetString("error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, cannot read tag.
        /// </summary>
        internal static string error3 {
            get {
                return ResourceManager.GetString("error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, cannot retrieve log state from VarioSens card.
        /// </summary>
        internal static string error4 {
            get {
                return ResourceManager.GetString("error4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, cannot get violation data.
        /// </summary>
        internal static string error5 {
            get {
                return ResourceManager.GetString("error5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No violations recorded.
        /// </summary>
        internal static string error6 {
            get {
                return ResourceManager.GetString("error6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, not a VarioSens tag.
        /// </summary>
        internal static string error7 {
            get {
                return ResourceManager.GetString("error7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to submit..
        /// </summary>
        internal static string FailedToSubmit {
            get {
                return ResourceManager.GetString("FailedToSubmit", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Gentag_logo {
            get {
                object obj = ResourceManager.GetObject("Gentag_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is available. You are running .
        /// </summary>
        internal static string IsAvailableYouAreRunning {
            get {
                return ResourceManager.GetString("IsAvailableYouAreRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Violation Log.
        /// </summary>
        internal static string logString {
            get {
                return ResourceManager.GetString("logString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo Limit.
        /// </summary>
        internal static string loLimitString {
            get {
                return ResourceManager.GetString("loLimitString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup.
        /// </summary>
        internal static string manualIDButtonInit {
            get {
                return ResourceManager.GetString("manualIDButtonInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description found.
        /// </summary>
        internal static string NoDescriptionFound {
            get {
                return ResourceManager.GetString("NoDescriptionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description yet.
        /// </summary>
        internal static string NoDescriptionYet {
            get {
                return ResourceManager.GetString("NoDescriptionYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found..
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ok {
            get {
                object obj = ResourceManager.GetObject("ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient information was not found..
        /// </summary>
        internal static string patientInfoNotFound {
            get {
                return ResourceManager.GetString("patientInfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible network error, please try again..
        /// </summary>
        internal static string PossibleNetworkErrorPleaseTryAgain {
            get {
                return ResourceManager.GetString("PossibleNetworkErrorPleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem connecting to web service: .
        /// </summary>
        internal static string ProblemConnectingToWebService {
            get {
                return ResourceManager.GetString("ProblemConnectingToWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with reader.
        /// </summary>
        internal static string ProblemWithReader {
            get {
                return ResourceManager.GetString("ProblemWithReader", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap question {
            get {
                object obj = ResourceManager.GetObject("question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Tag.
        /// </summary>
        internal static string readIDButtonInit {
            get {
                return ResourceManager.GetString("readIDButtonInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read VarioSens.
        /// </summary>
        internal static string readLogButtonInit {
            get {
                return ResourceManager.GetString("readLogButtonInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Values.
        /// </summary>
        internal static string readValueButtonInit {
            get {
                return ResourceManager.GetString("readValueButtonInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results recorded..
        /// </summary>
        internal static string ResultsRecorded {
            get {
                return ResourceManager.GetString("ResultsRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Values.
        /// </summary>
        internal static string setValueButtonInit {
            get {
                return ResourceManager.GetString("setValueButtonInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: .
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VarioSens.
        /// </summary>
        internal static string tab1String {
            get {
                return ResourceManager.GetString("tab1String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Lookup.
        /// </summary>
        internal static string tab2String {
            get {
                return ResourceManager.GetString("tab2String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string tab3String {
            get {
                return ResourceManager.GetString("tab3String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VarioSens/W.
        /// </summary>
        internal static string tab4String {
            get {
                return ResourceManager.GetString("tab4String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gentag Demo.
        /// </summary>
        internal static string titleString {
            get {
                return ResourceManager.GetString("titleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unexpected: .
        /// </summary>
        internal static string Unexpected {
            get {
                return ResourceManager.GetString("Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version .
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
