//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1318
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.1318.
// 
namespace COREMobileMedDemo.COREMedDemoWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="COREMedDemoWSSoapHttp", Namespace="http://COREMedDemo/")]
    public partial class COREMedDemoWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public COREMedDemoWS() {
            this.Url = "http://crius.dyndns.org:8888/GentagDemo/COREMedDemoWSSoapHttpPort";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://COREMedDemo/", ResponseNamespace="http://COREMedDemo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public errorReport enterDrugInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] drugInfo newDrug) {
            object[] results = this.Invoke("enterDrugInfo", new object[] {
                        newDrug});
            return ((errorReport)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginenterDrugInfo(drugInfo newDrug, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("enterDrugInfo", new object[] {
                        newDrug}, callback, asyncState);
        }
        
        /// <remarks/>
        public errorReport EndenterDrugInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((errorReport)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://COREMedDemo/", ResponseNamespace="http://COREMedDemo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public errorReport enterPatientPhoto([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] patientRecord newPatient) {
            object[] results = this.Invoke("enterPatientPhoto", new object[] {
                        newPatient});
            return ((errorReport)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginenterPatientPhoto(patientRecord newPatient, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("enterPatientPhoto", new object[] {
                        newPatient}, callback, asyncState);
        }
        
        /// <remarks/>
        public errorReport EndenterPatientPhoto(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((errorReport)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://COREMedDemo/", ResponseNamespace="http://COREMedDemo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public errorReport enterPatientRecord([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] patientRecord newPatient) {
            object[] results = this.Invoke("enterPatientRecord", new object[] {
                        newPatient});
            return ((errorReport)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginenterPatientRecord(patientRecord newPatient, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("enterPatientRecord", new object[] {
                        newPatient}, callback, asyncState);
        }
        
        /// <remarks/>
        public errorReport EndenterPatientRecord(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((errorReport)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://COREMedDemo/", ResponseNamespace="http://COREMedDemo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public patientRecord getPatientRecord([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string RFIDNum) {
            object[] results = this.Invoke("getPatientRecord", new object[] {
                        RFIDNum});
            return ((patientRecord)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPatientRecord(string RFIDNum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPatientRecord", new object[] {
                        RFIDNum}, callback, asyncState);
        }
        
        /// <remarks/>
        public patientRecord EndgetPatientRecord(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((patientRecord)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://COREMedDemo/", ResponseNamespace="http://COREMedDemo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public errorReport logPatientVitals([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string RFIDNum, [System.Xml.Serialization.XmlElementAttribute("temperatures")] float[] temperatures, int periodicity) {
            object[] results = this.Invoke("logPatientVitals", new object[] {
                        RFIDNum,
                        temperatures,
                        periodicity});
            return ((errorReport)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginlogPatientVitals(string RFIDNum, float[] temperatures, int periodicity, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("logPatientVitals", new object[] {
                        RFIDNum,
                        temperatures,
                        periodicity}, callback, asyncState);
        }
        
        /// <remarks/>
        public errorReport EndlogPatientVitals(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((errorReport)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://COREMedDemo/")]
    public partial class drugInfo {
        
        private string rFIDNumField;
        
        private byte[] pictureField;
        
        private string descriptionField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RFIDNum {
            get {
                return this.rFIDNumField;
            }
            set {
                this.rFIDNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] picture {
            get {
                return this.pictureField;
            }
            set {
                this.pictureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://COREMedDemo/")]
    public partial class patientRecord {
        
        private byte[] imageField;
        
        private bool existsField;
        
        private string middleNameField;
        
        private string[] allergiesField;
        
        private string[] medicationsField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string rFIDnumField;
        
        private long dOBField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        public bool exists {
            get {
                return this.existsField;
            }
            set {
                this.existsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string middleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("allergies", IsNullable=true)]
        public string[] allergies {
            get {
                return this.allergiesField;
            }
            set {
                this.allergiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("medications", IsNullable=true)]
        public string[] medications {
            get {
                return this.medicationsField;
            }
            set {
                this.medicationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RFIDnum {
            get {
                return this.rFIDnumField;
            }
            set {
                this.rFIDnumField = value;
            }
        }
        
        /// <remarks/>
        public long DOB {
            get {
                return this.dOBField;
            }
            set {
                this.dOBField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://COREMedDemo/")]
    public partial class errorReport {
        
        private string errorMessageField;
        
        private int errorCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
    }
}
